# Generated by Django 4.1.1 on 2022-09-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PdfSearchApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="files",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
