# Generated by Django 4.1.1 on 2022-10-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PdfSearchApp", "0002_alter_files_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="WordFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="wordfiles")),
            ],
            options={
                "db_table": "wordfiles",
            },
        ),
    ]
